[tool.poetry]
name = "lineart"
version = "0.1.0"
description = ""
authors = ["Leo Browning <leo.browning@qrious.co.nz>"]

[tool.poetry.dependencies]
python = "^3.8"
jupyterlab = "^2.2.9"
numpy = "^1.19.4"
flat = "^0.3.2"
dask = "^2.30.0"
toolz = "^0.11.1"
cloudpickle = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
flake8 = "^3.8.4"
black = "^20.8b1"
rope = "^0.18.0"
matplotlib = "^3.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
